name: Deploy To S3 And Invalidate Cloudfront

on:
  push:
    branches:
      - main

jobs:
  my-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: github repository 파일 불러오기
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm i

      # - name: 디렉토리 출력하기
      #   run: ls

      - name: 빌드하기
        run: npm run build

      - name: 디렉토리 출력하기
        run: ls